import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'dictation_trace.dart';

/// Vocabulary mined from this machine's Claude Code transcripts.
///
/// The recogniser is tuned for general English and mangles project nouns —
/// "Convex" becomes "convicts", "e2e" becomes "eat to eat". [terms] biases it
/// back; [phrases] trains an on-device custom language model; [persona]
/// describes the user's prompt style for any downstream cleanup pass.
///
/// Generated by `scripts/mine_dictation_vocabulary.py`. Absent on a fresh
/// clone, in which case dictation still works — just untuned.
@immutable
class DictationVocabulary {
  const DictationVocabulary({
    required this.terms,
    required this.phrases,
    required this.persona,
  });

  static const empty = DictationVocabulary(terms: [], phrases: [], persona: {});

  final List<String> terms;
  final List<String> phrases;
  final Map<String, Object?> persona;

  bool get isEmpty => terms.isEmpty && phrases.isEmpty;

  /// Merge a checked-in seed list ahead of the mined terms.
  ///
  /// Mined terms come first because they are ranked by how much this user
  /// actually says them, and the native side truncates the list. The seed then
  /// fills the remaining slots with the team vocabulary this machine happens
  /// not to have mined yet — the case that matters on a fresh clone, where
  /// there is nothing mined at all.
  DictationVocabulary withSeed(List<String> seed) {
    if (seed.isEmpty) return this;
    final seen = {for (final term in terms) term.toLowerCase()};
    final merged = [...terms];
    for (final term in seed) {
      if (seen.add(term.toLowerCase())) merged.add(term);
    }
    return DictationVocabulary(
      terms: merged,
      phrases: phrases,
      persona: persona,
    );
  }

  /// Identifies this phrase set so the native side retrains the language model
  /// only when the vocabulary actually changed. Re-mining with no new prompts
  /// yields the same version and reuses the cached model.
  String get version {
    if (phrases.isEmpty) return 'empty';
    return Object.hashAll(phrases).toUnsigned(32).toRadixString(16);
  }

  static DictationVocabulary parse(String source) {
    final decoded = jsonDecode(source);
    if (decoded is! Map) return empty;
    List<String> strings(Object? raw) => raw is List
        ? raw.whereType<String>().where((s) => s.trim().isNotEmpty).toList()
        : const [];
    return DictationVocabulary(
      terms: strings(decoded['terms']),
      phrases: strings(decoded['phrases']),
      persona: decoded['persona'] is Map
          ? Map<String, Object?>.from(decoded['persona'] as Map)
          : const {},
    );
  }
}

/// Languages dictation can be decoded as.
///
/// Separate from the phone's language on purpose. Apple picks the acoustic and
/// language model from this locale, so a phone set to Portuguese decodes
/// English speech through a Portuguese model — which does not mangle a word
/// here and there, it returns unrelated words for whole clauses. Most of this
/// team speaks English tech vocabulary on non-English phones, so the default is
/// English regardless of the system setting.
abstract final class DictationLocale {
  static const fallback = 'en-US';

  /// Identifier -> label, in the order the picker shows them.
  static const options = <String, String>{
    'en-US': 'English (US)',
    'en-GB': 'English (UK)',
    'pt-BR': 'Português (Brasil)',
    'pt-PT': 'Português (Portugal)',
    'es-ES': 'Español',
    'fr-FR': 'Français',
    'de-DE': 'Deutsch',
    'it-IT': 'Italiano',
  };

  static String label(String id) => options[id] ?? id;

  static String normalize(String? id) =>
      id != null && options.containsKey(id) ? id : fallback;
}

/// What the recogniser is doing right now.
enum DictationState { idle, listening, unavailable }

/// A transcript update.
///
/// [isFinal] means "bank this" - the recogniser has committed these words and
/// will never revise them. It does *not* mean the session ended: iOS rotates
/// recognition tasks roughly every minute, and each rotation banks a segment
/// while dictation carries on. The stream closing is what ends a session.
@immutable
class DictationResult {
  const DictationResult({required this.text, required this.isFinal});

  final String text;
  final bool isFinal;
}

/// Why dictation could not start. Surfaced so the UI can route the user to
/// Settings rather than showing a dead button.
enum DictationError { speechDenied, microphoneDenied, unavailable, failed }

/// On-device dictation.
///
/// Two native engines sit behind this one channel. On iOS 26 it is
/// `ios/Runner/DictationAnalyzer.swift` (`SpeechAnalyzer`) — a better speech
/// model, and the one this is tuned for. Below that, and whenever the newer
/// model has not finished downloading, it is `ios/Runner/Dictation.swift`
/// (`SFSpeechRecognizer`). Both are biased toward this user's vocabulary, both
/// emit the same events, and audio never leaves the device on either.
class DictationService {
  DictationService({AssetBundle? bundle, DictationTrace? trace})
      : _bundle = bundle ?? rootBundle,
        trace = trace ?? DictationTrace(send: (_) async {});

  /// Diagnostics sink. Off unless enabled from Settings.
  final DictationTrace trace;

  static const _methods = MethodChannel('panda_code/dictation');
  static const _events = EventChannel('panda_code/dictation/events');
  static const _asset = 'assets/dictation_vocabulary.json';
  static const _seedAsset = 'assets/dictation_seed_vocabulary.json';

  final AssetBundle _bundle;

  DictationVocabulary _vocabulary = DictationVocabulary.empty;
  DictationVocabulary get vocabulary => _vocabulary;

  /// Language the recogniser decodes speech as.
  ///
  /// Set from Settings; see [DictationLocale]. Not the phone's language: this
  /// team dictates English tech vocabulary into phones set to other languages,
  /// and decoding that through the wrong language model garbles whole clauses,
  /// not just project nouns.
  String _locale = DictationLocale.fallback;
  set locale(String value) {
    final next = value.trim().isEmpty ? DictationLocale.fallback : value.trim();
    if (next == _locale) return;
    _locale = next;
    // The custom language model is exported per-locale, so it has to be
    // retrained before the next session in the new language.
    _prepared = false;
  }

  bool _prepared = false;
  StreamSubscription<dynamic>? _subscription;

  /// True where the native channel exists at all.
  bool get isSupported => !kIsWeb && Platform.isIOS;

  /// Load the mined vocabulary and train the custom language model.
  ///
  /// Safe to call repeatedly; the work happens once. Training takes a few
  /// seconds on first run for a given vocabulary version and is then cached on
  /// disk by the native side, so this is called ahead of the first tap rather
  /// than during it.
  Future<void> prepare() async {
    if (_prepared || !isSupported) return;
    _prepared = true;

    DictationVocabulary mined = DictationVocabulary.empty;
    try {
      mined = DictationVocabulary.parse(await _bundle.loadString(_asset));
    } on FlutterError {
      // No mined vocabulary on this machine — the seed list still applies.
    } catch (error) {
      debugPrint('[dictation] vocabulary unreadable: $error');
    }
    _vocabulary = mined.withSeed(await _loadSeedTerms());

    // Called even with no mined phrases: on iOS 26 this is also where the
    // native side downloads the SpeechAnalyzer model for the chosen language,
    // which has nothing to do with the vocabulary and must not be skipped on a
    // fresh clone. Until it lands, dictation falls back to the older engine.
    try {
      await _methods.invokeMethod<bool>('prepare', {
        'phrases': _vocabulary.phrases,
        // The trained model is cached under this version, and it is only valid
        // for the locale it was exported for — so the locale is part of it.
        'version': '${_vocabulary.version}-$_locale',
        'locale': _locale,
      });
    } catch (error) {
      // The custom model is an enhancement; contextual strings still apply.
      debugPrint('[dictation] language model unavailable: $error');
    }
  }

  /// The checked-in team bias list. Ships with the app, so it is present even
  /// when nothing has been mined on this machine.
  Future<List<String>> _loadSeedTerms() async {
    try {
      final decoded = jsonDecode(await _bundle.loadString(_seedAsset));
      if (decoded is! Map) return const [];
      final raw = decoded['terms'];
      if (raw is! List) return const [];
      return raw
          .whereType<String>()
          .map((s) => s.trim())
          .where((s) => s.isNotEmpty)
          .toList();
    } catch (error) {
      debugPrint('[dictation] seed vocabulary unreadable: $error');
      return const [];
    }
  }

  /// Request both grants dictation needs: speech recognition and the mic.
  Future<DictationError?> authorize() async {
    if (!isSupported) return DictationError.unavailable;
    try {
      final status = await _methods.invokeMethod<String>('authorize');
      switch (status) {
        case 'granted':
          return null;
        case 'speech_denied':
          return DictationError.speechDenied;
        case 'microphone_denied':
          return DictationError.microphoneDenied;
        default:
          return DictationError.failed;
      }
    } catch (error) {
      debugPrint('[dictation] authorize failed: $error');
      return DictationError.failed;
    }
  }

  /// Begin listening. Emits partial transcripts as the user speaks, then one
  /// final result. The stream closes when recognition ends.
  Stream<DictationResult> start() {
    final controller = StreamController<DictationResult>();

    Future<void> begin() async {
      await prepare();
      final denied = await authorize();
      if (denied != null) {
        controller.addError(denied);
        await controller.close();
        return;
      }

      _subscription = _events.receiveBroadcastStream().listen(
        (event) {
          if (event is! Map) return;
          final payload = Map<Object?, Object?>.from(event);
          final type = payload['type'];
          if (type == 'trace') {
            // Native diagnostics ride the same channel as transcripts.
            trace.add(
              payload['event'] as String? ?? 'native.?',
              gen: payload['gen'] as int?,
              textLen: payload['textLen'] as int?,
              note: payload['note'] as String?,
            );
            return;
          }
          if (type == 'error') {
            controller.addError(DictationError.failed);
            unawaited(controller.close());
            return;
          }
          final text = payload['text'];
          if (text is! String) return;
          switch (type) {
            case 'partial':
              controller.add(DictationResult(text: text, isFinal: false));
            case 'segment':
              // A task rotated. Bank the words; the session continues.
              controller.add(DictationResult(text: text, isFinal: true));
            case 'final':
              if (text.isNotEmpty) {
                controller.add(DictationResult(text: text, isFinal: true));
              }
              unawaited(controller.close());
          }
        },
        onError: (Object error) {
          controller.addError(DictationError.failed);
          unawaited(controller.close());
        },
      );

      try {
        await _methods.invokeMethod<void>('start', {
          'contextualStrings': _vocabulary.terms,
          'locale': _locale,
          'onDevice': true,
          'punctuation': true,
        });
      } catch (error) {
        debugPrint('[dictation] start failed: $error');
        controller.addError(DictationError.failed);
        await controller.close();
      }
    }

    controller.onCancel = () async {
      await _subscription?.cancel();
      _subscription = null;
    };
    unawaited(begin());
    return controller.stream;
  }

  /// Abandon the in-flight task and open a fresh one, without ending the
  /// session or emitting a transcript for the discarded task.
  ///
  /// Call this when the composer text changed out from under dictation (a
  /// manual edit mid-utterance): the current task's next partial would still
  /// narrate the pre-edit wording, so continuing it would restate what was
  /// just corrected. A fresh task's first partial is relative to the new text.
  Future<void> restart() async {
    trace.add('dart.restart');
    if (!isSupported) return;
    try {
      await _methods.invokeMethod<void>('restart');
    } catch (error) {
      debugPrint('[dictation] restart failed: $error');
    }
  }

  /// Stop listening and let the recogniser flush a final transcript.
  Future<void> stop() async {
    trace.add('dart.stop');
    if (!isSupported) return;
    try {
      await _methods.invokeMethod<void>('stop');
    } catch (error) {
      debugPrint('[dictation] stop failed: $error');
    }
  }

  /// Abandon the utterance; no final transcript is emitted.
  Future<void> cancel() async {
    await _subscription?.cancel();
    _subscription = null;
    if (!isSupported) return;
    try {
      await _methods.invokeMethod<void>('cancel');
    } catch (error) {
      debugPrint('[dictation] cancel failed: $error');
    }
  }
}
